# Generated by Django 5.1.8 on 2025-06-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0241_domain_has_security_txt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("THEORY", "Theory Content"),
                            ("PRACTICAL", "Practical Exercise"),
                            ("SIMULATION", "Interactive Simulation"),
                            ("QUIZ", "Quiz"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Main content of the lesson")),
                ("order", models.PositiveIntegerField()),
                (
                    "duration",
                    models.PositiveIntegerField(blank=True, help_text="Estimated duration in minutes", null=True),
                ),
                (
                    "simulation_config",
                    models.JSONField(
                        blank=True,
                        help_text="Configuration for interactive simulations (e.g., initial setup for SQL injection practice)",
                        null=True,
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="website.lab"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "question_type",
                    models.CharField(
                        choices=[("MCQ", "Multiple Choice"), ("CODING", "Coding Question"), ("TEXT", "Text Answer")],
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="For MCQ: list of options. For coding: test cases and expected outputs",
                        null=True,
                    ),
                ),
                ("correct_answer", models.TextField(help_text="Correct answer or solution")),
                ("explanation", models.TextField(blank=True, help_text="Explanation of the correct answer", null=True)),
                ("points", models.PositiveIntegerField(default=1)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="website.lesson"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer", models.TextField()),
                ("is_correct", models.BooleanField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.question")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.userprofile")),
            ],
            options={
                "unique_together": {("user", "question")},
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("lab", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.lab")),
                ("lesson", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.lesson")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="website.userprofile")),
            ],
            options={
                "unique_together": {("user", "lab", "lesson")},
            },
        ),
    ]
