# Generated by Django 5.1.8 on 2025-06-29 12:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0242_lab_lesson_question_useranswer_userprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={"ordering": ["lab__order", "lesson__order"]},
        ),
        migrations.RenameField(
            model_name="userprogress",
            old_name="last_accessed",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="points_earned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="completed_techniques",
            field=models.JSONField(
                blank=True, default=list, help_text="List of successfully completed injection techniques"
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="points_earned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lab",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
