# Generated by Django 5.1.8 on 2025-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0243_alter_userprogress_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="simulation_config",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("THEORY", "Theory Content"),
                    ("SQL_INJECTION", "SQL Injection Practice"),
                    ("XSS", "Cross-Site Scripting Practice"),
                    ("FILE_UPLOAD", "File Upload Practice"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="completed_techniques",
            field=models.JSONField(blank=True, default=list, help_text="List of successfully completed techniques"),
        ),
    ]
