# Generated by Django 5.1.8 on 2025-06-29 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0244_remove_lesson_simulation_config_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={"ordering": ["lesson__order"]},
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="duration",
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "lesson")},
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[("theory", "Theory"), ("simulation", "Simulation")], default="theory", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="simulation_type",
            field=models.CharField(
                blank=True,
                choices=[("sql_injection", "SQL Injection")],
                help_text="Type of simulation for simulation lessons",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(help_text="Main content or instructions for the lesson"),
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="completed_techniques",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="lab",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="last_attempt_at",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="points_earned",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="status",
        ),
    ]
