# Generated by Django 5.1.8 on 2025-06-29 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0245_alter_userprogress_options_and_more"),
    ]

    operations = [
        # First remove any foreign key constraints
        migrations.RemoveField(
            model_name="useranswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="question",
            name="lesson",
        ),
        
        # Then update UserProgress model
        migrations.AlterModelOptions(
            name="userprogress",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="userprogress",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="points_earned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        
        # Finally delete the models
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="UserAnswer",
        ),
    ]
